name: toot
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '@announce')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version: 20
      - name: Announce to Mastodon
        run: node toot/announce.js
        env:
            MASTODON_AUTH_TOKEN: ${{ secrets.TOOT_TOKEN }}